### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by stevefloat** [verbb/social-feeds#2]
### Describe the bug

When attempting to preview a feed, either in the admin pages or when rendering in templates I get the following error:

```
AxiosError: Request failed with status code 500
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'idx_udicjkgychshafwsjgwnjduqngdiwmlfnlsl' The SQL being executed was: INSERT INTO `socialfeeds_posts` (`sourceId`, `cacheKey`, `postId`, `data`, `datePosted`, `dateCreated`, `dateUpdated`, `uid`) VALUES (1, 'b5881510b4aa660d7cf6bdfc0ebb80c8', '1508803334345572358', '{\"id\":\"1508803334345572358\",\"uid\":null,\"title\":null,\"text\":\"...
```

My 'Source' has been successfully set up and connected to Twitter. All looks good from that point of view.

Any help or guidance would be appreciated.

### Steps to reproduce

1. Set up a source
2. Set up a feed
3. Attempt to preview in Admin (Feed > Preview press 'load posts') or render in template using {{ craft.socialFeeds.renderPosts('nameOfFeed') }}

### Craft CMS version

4.3.10

### Plugin version

1.0.0

### Multi-site?

No

### Additional context

Recently upgraded from Craft3 to Craft4, however everything else looks okay.

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/social-feeds:"dev-craft-4 as 1.0.0"`.

**Comment by stevefloat** [comment]
Hi Josh

I've pulled this down to get the update and have confirmed I'm running **dev-craft-4**, however I still see the same issue. I've run `clear-caches/all` and `migrate/all` however still seeing the same Integrity Constraint error.

Should I need to do anything else?

Thanks,
Stephen

**Comment by engram-design** [comment]
Hmm, that's a _little_ strange as I can't seem to replicate it. I might suggest deleting the cache of the posts from Utilities > Social Feeds.

**Comment by stevefloat** [comment]
I've just done as you suggest and use Utilities > Social Feeds to delete the cache. Checking the db table `socialfeeds_posts` I can see it's empty.

Then when attempting to preview the feed (either in admin or frontend) I still get the same error.
I can see a new row has been inserted into the db table

Direct from the logs:

```
$_POST = []
2023-03-03 11:42:11 [ERROR] Error refreshing posts for source “mySource”: “SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'idx_udicjkgychshafwsjgwnjduqngdiwmlfnlsl'
The SQL being executed was: INSERT INTO `socialfeeds_posts` (`sourceId`, `cacheKey`, `postId`, `data`, `datePosted`, `dateCreated`, `dateUpdated`, `uid`) VALUES (1, 'b5881510b4aa660d7cf6bdfc0ebb80c8', '1508803334345572358', '{xxx}', '2022-03-29 13:48:41', '2023-03-03 11:42:11', '2023-03-03 11:42:11', '975c2eaa-f052-4350-8dbd-4c696f9a429f')” /xxx/vendor/yiisoft/yii2/db/Schema.php:676
2023-03-03 11:42:11 [INFO] Request context:
$_GET = [
    'v' => '1677843729362'
]
```

**Comment by engram-design** [comment]
Ah, I see the issue! My own install was actually out of date with its database schema, which is why I wasn't seeing this.

Should be fixed up now, if you run `composer require verbb/social-feeds:"dev-craft-4 as 1.0.0"` one last time.

**Comment by stevefloat** [comment]
That did it - thanks Josh!

**Comment by engram-design** [comment]
Fixed in [1.0.1](https://github.com/verbb/social-feeds/releases/tag/1.0.1)
